version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=your-username
      - POSTGRES_PASSWORD=your-password
      - POSTGRES_DB=your-database
    ports:
      - "5432:5432"
    volumes:
      - ./backend/pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://your-username:your-password@db:5432/your-database
    command: npm run dev
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend